// src/templates/examples/ai/web/react/next/src/app/ai/page.tsx
"use client";

import { useChat } from "@ai-sdk/react";
import { Send } from "lucide-react";
import { useRef, useEffect } from "react";

// @ts-expect-error <dler-remove-comment>
import { Button } from "@/components/ui/button";
// @ts-expect-error <dler-remove-comment>
import { Input } from "@/components/ui/input";

export default function AIPage() {
  const { messages, input, handleInputChange, handleSubmit } = useChat({
    api: `${process.env.NEXT_PUBLIC_SERVER_URL}/ai`,
  });

  const messagesEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  return (
    <div className="grid grid-rows-[1fr_auto] overflow-hidden w-full mx-auto p-4">
      <div className="overflow-y-auto space-y-4 pb-4">
        {messages.length === 0 ? (
          <div className="text-center text-muted-foreground mt-8">
            Ask me anything to get started!
          </div>
        ) : (
          messages.map((message) => (
            <div
              key={message.id}
              className={`p-3 rounded-lg ${
                message.role === "user"
                  ? "bg-primary/10 ml-8"
                  : "bg-secondary/20 mr-8"
              }`}
            >
              <p className="text-sm font-semibold mb-1">
                {message.role === "user" ? "You" : "AI Assistant"}
              </p>
              <div className="whitespace-pre-wrap">{message.content}</div>
            </div>
          ))
        )}
        <div ref={messagesEndRef} />
      </div>

      <form
        onSubmit={handleSubmit}
        className="w-full flex items-center space-x-2 pt-2 border-t"
      >
        <Input
          name="prompt"
          value={input}
          onChange={handleInputChange}
          placeholder="Type your message..."
          className="flex-1"
          autoComplete="off"
          autoFocus
        />
        <Button type="submit" size="icon">
          <Send size={18} />
        </Button>
      </form>
    </div>
  );
}

// src/templates/examples/ai/web/nuxt/app/pages/ai.vue
<script setup lang="ts">
import { useChat } from "@ai-sdk/vue";
import { nextTick, ref, watch } from "vue";

const config = useRuntimeConfig();
const serverUrl = config.public.serverURL;

const { messages, input, handleSubmit } = useChat({
  api: `${serverUrl}/ai`,
});

const messagesEndRef = ref<null | HTMLDivElement>(null);

watch(messages, async () => {
  await nextTick();
  messagesEndRef.value?.scrollIntoView({ behavior: "smooth" });
});

function getMessageText(message: any) {
  return message.parts
    .filter((part: any) => part.type === "text")
    .map((part: any) => part.text)
    .join("");
}
</script>

<template>
  <div class="grid grid-rows-[1fr_auto] overflow-hidden w-full mx-auto p-4">
    <div class="overflow-y-auto space-y-4 pb-4">
      <div v-if="messages.length === 0" class="text-center text-muted-foreground mt-8">
        Ask me anything to get started!
      </div>
      <div
        v-for="message in messages"
        :key="message.id"
        :class="[
          'p-3 rounded-lg',
          message.role === 'user' ? 'bg-primary/10 ml-8' : 'bg-secondary/20 mr-8'
        ]"
      >
        <p class="text-sm font-semibold mb-1">
          {{ message.role === 'user' ? 'You' : 'AI Assistant' }}
        </p>
        <div class="whitespace-pre-wrap">{{ getMessageText(message) }}</div>
      </div>
      <div ref="messagesEndRef" />
    </div>

    <form @submit.prevent="handleSubmit" class="w-full flex items-center space-x-2 pt-2 border-t">
      <UInput
        name="prompt"
        v-model="input"
        placeholder="Type your message..."
        class="flex-1"
        autocomplete="off"
        autofocus
      />
      <UButton type="submit" color="primary" size="md" square>
        <UIcon name="i-lucide-send" class="w-5 h-5" />
      </UButton>
    </form>
  </div>
</template>
