// src/templates/auth/web/svelte/src/routes/dashboard/+page.svelte
<script lang="ts">
import { onMount } from "svelte";
import { goto } from "$app/navigation";
import { authClient } from "$lib/auth-client";
import { orpc } from "$lib/orpc";
import { createQuery } from "@tanstack/svelte-query";
import { get } from "svelte/store";

const sessionQuery = authClient.useSession();

const privateDataQuery = createQuery(orpc.privateData.queryOptions());

onMount(() => {
  const { data: session, isPending } = get(sessionQuery);
  if (!session && !isPending) {
    goto("/login");
  }
});
</script>

{#if $sessionQuery.isPending}
	<div>Loading...</div>
{:else if !$sessionQuery.data}
	<!-- Redirecting... -->
{:else}
	<div>
		<h1>Dashboard</h1>
		<p>Welcome {$sessionQuery.data.user.name}</p>
		<p>privateData: {$privateDataQuery.data?.message}</p>
	</div>
{/if}

// src/templates/auth/web/nuxt/app/pages/dashboard.vue
<script setup lang="ts">
import { useQuery } from "@tanstack/vue-query";
const { $authClient } = useNuxtApp();

definePageMeta({
  middleware: ["auth"],
});

const { $orpc } = useNuxtApp();

const session = $authClient.useSession();

const privateData = useQuery($orpc.privateData.queryOptions());
</script>

<template>
  <div class="container mx-auto p-4">
      <h1 class="text-2xl font-bold mb-4">Dashboard</h1>
     <div v-if="session?.data?.user">
        <p class="mb-2">Welcome {{ session.data.user.name }}</p>
     </div>
        <div v-if="privateData.status.value === 'pending'">Loading private data...</div>
        <div v-else-if="privateData.status.value === 'error'">Error loading private data: {{ privateData.error.value?.message }}</div>
        <p v-else-if="privateData.data.value">Private Data: {{ privateData.data.value.message }}</p>
  </div>
</template>
