// src/templates/auth/web/react/next/src/app/login/page.tsx
"use client";

import { useState } from "react";

// @ts-expect-error dler-remove-comment
import SignInForm from "@/components/sign-in-form";
// @ts-expect-error dler-remove-comment
import SignUpForm from "@/components/sign-up-form";

export default function LoginPage() {
  const [showSignIn, setShowSignIn] = useState(false);

  return showSignIn ? (
    <SignInForm onSwitchToSignUp={() => setShowSignIn(false)} />
  ) : (
    <SignUpForm onSwitchToSignIn={() => setShowSignIn(true)} />
  );
}

// src/templates/auth/web/nuxt/app/pages/login.vue
<script setup lang="ts">
// @ts-expect-error dler-remove-comment
const { $authClient } = useNuxtApp();
// @ts-expect-error dler-remove-comment
import SignInForm from "~/components/SignInForm.vue";
// @ts-expect-error dler-remove-comment
import SignUpForm from "~/components/SignUpForm.vue";

const session = $authClient.useSession();
// @ts-expect-error dler-remove-comment
const showSignIn = ref(true);

// @ts-expect-error dler-remove-comment
watchEffect(() => {
  if (!session?.value.isPending && session?.value.data) {
    // @ts-expect-error dler-remove-comment
    navigateTo("/dashboard", { replace: true });
  }
});
</script>

<template>
  <div>
    <Loader v-if="session.isPending" />
    <div v-else-if="!session.data">
      <SignInForm v-if="showSignIn" @switch-to-sign-up="showSignIn = false" />
      <SignUpForm v-else @switch-to-sign-in="showSignIn = true" />
    </div>
  </div>
</template>
